# Generated by Django 5.1 on 2024-08-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
