# Generated by Django 5.1 on 2024-08-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_has_set_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='created_assessments',
        ),
    ]
