# Generated by Django 5.1 on 2024-08-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_true',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
