# Generated by Django 5.1 on 2024-09-01 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_name'),
        ('questions', '0003_alter_question_is_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course'),
            preserve_default=False,
        ),
    ]
