# Generated by Django 5.1 on 2024-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='questions',
        ),
        migrations.AddField(
            model_name='assessment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
