# Generated by Django 5.1 on 2024-08-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_assessment_questions_assessment_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='is_live',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='assessment',
            name='passing_marks',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_limit',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
