# Generated by Django 5.1 on 2024-08-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_rename_is_live_assessment_is_published_and_more'),
        ('courses', '0003_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course'),
            preserve_default=False,
        ),
    ]
